// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX9DRkshBTY4pu9eNoqeYVLR9HEtbk_rA',
    appId: '1:909376539195:web:0353312ec6ac6d76892a1e',
    messagingSenderId: '909376539195',
    projectId: 'banaripara',
    authDomain: 'banaripara.firebaseapp.com',
    storageBucket: 'banaripara.firebasestorage.app',
    measurementId: 'G-PVBXEX2SNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmCYZToa4HQlaWmkN2PLGGYYGvqg2EAfM',
    appId: '1:909376539195:android:e15bb9993d1a6a8a892a1e',
    messagingSenderId: '909376539195',
    projectId: 'banaripara',
    storageBucket: 'banaripara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFF2g8BAoTNff0woX8JVgBN4ikSJvgA1g',
    appId: '1:909376539195:ios:3aaaaa5afd114c40892a1e',
    messagingSenderId: '909376539195',
    projectId: 'banaripara',
    storageBucket: 'banaripara.firebasestorage.app',
    iosBundleId: 'com.example.banaripara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFF2g8BAoTNff0woX8JVgBN4ikSJvgA1g',
    appId: '1:909376539195:ios:3aaaaa5afd114c40892a1e',
    messagingSenderId: '909376539195',
    projectId: 'banaripara',
    storageBucket: 'banaripara.firebasestorage.app',
    iosBundleId: 'com.example.banaripara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX9DRkshBTY4pu9eNoqeYVLR9HEtbk_rA',
    appId: '1:909376539195:web:f517e4cb06ddbc58892a1e',
    messagingSenderId: '909376539195',
    projectId: 'banaripara',
    authDomain: 'banaripara.firebaseapp.com',
    storageBucket: 'banaripara.firebasestorage.app',
    measurementId: 'G-2BWWC13ERD',
  );
}
